### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by padak** [keboola/tableau-server-writer#1]
V Zeealandii nestačí hodina timeoute na poslání 1.5GB do Tableau Serveru, hostovanýho v Tableau.

Example job: https://connection.keboola.com/admin/projects/918/jobs/168152361?q=
Example cfg: https://connection.keboola.com/admin/projects/918/writers/tde-exporter/experimental-34

Kdyby se ty timeoute daly parametrizovat, třeba přes Manage API, bylo by to super - tady to asi budeme muset zvednout.

FYI

**Comment by Halama** [comment]
Parametrizovat a nastavovat to jde. Zatim ale jenom globalne pro konkretni komponentu ne konkretni projekt, konfiguraci nebo job.

**Comment by Halama** [comment]
koukam ze ten timeout je ale zrovna pro tde-exporter nastaveny brutalne vysokej. Nemenil si ho ted?

**Comment by Halama** [comment]
Activity log zmen komponent a vsehoje taky v roadmape abych se nemusel takhle blbe ptat nebo zkoumat kdo to kdy zmenil :)

**Comment by Halama** [comment]
Aha tenhle job co odkazujes patri `wr-tableau-server` a ten ma default hodinovy limit.

**Comment by padak** [comment]
@Halama já bych na tohle nikdy nesahal. muzem to teda zvednou pro komponentu toho writeru na 3 hodiny?

**Comment by Halama** [comment]
Asi by se ty limity ruznych komponent ktere by pretezovaly defaulty taky daly pridelit projektu.

**Comment by Halama** [comment]
zvednu to ted na 3 h teda

**Comment by padak** [comment]
díky!

**Comment by Halama** [comment]
je to nastaveny na 3 hod

**Comment by Halama** [comment]
Tohle zatim zaviram
